#!/usr/bin/env python
"""Repack + JAR-sign the client APK with a patched asset, without a JDK.

Why this exists
---------------
The 7350 build-up animation layout (`assets/bundle/layout_buildup_animation.xml`)
lives *inside* the APK: the client resolves `bundle/<name>.xml` against its own
package archive, not against any writable directory (verified 2026-10-04 - a
copy dropped into `/sdcard/Android/data/<pkg>/files/bundle/`, `/sdcard/bundle/`
and `/data/data/<pkg>/files/bundle/` is ignored, and `librooneyj.so` contains no
AssetManager/AAsset strings while carrying 22 `FileInputStream` JNI references).
So the only way to change a layout is to edit the APK.

The device runs Android 5.1 (API 22): APK Signature Scheme v2 does not exist
there, so a plain JAR (v1) signature is enough. That is what this script
produces - v1 needs no special tooling, only a PKCS#7 blob over CERT.SF.

Entry bytes are copied verbatim from the source archive (no re-compression), so
everything except the replaced asset stays byte-identical.

    python scripts/patch-client-apk.py \
        --src apk/com.square_enix.million_cn-1.0.0.100.0712.M330.apk \
        --replace assets/bundle/layout_buildup_animation.xml=runtime/exp/bundle/layout_buildup_animation.xml \
        --out dist/kakusen-client-patched.apk \
        --key runtime/keys/kakusen-mod.pem --cert runtime/keys/kakusen-mod.crt
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import os
import shutil
import struct
import subprocess
import sys
import zipfile
from pathlib import Path

# Entries that carry the JAR signature. Anything with these names in META-INF is
# dropped from the source archive and regenerated by us.
SIG_BASENAMES = ("MANIFEST.MF",)
SIG_EXTS = (".SF", ".RSA", ".DSA", ".EC")
NEW_SIG_NAME = "CERT"


def sha1_b64(data: bytes) -> str:
    return base64.b64encode(hashlib.sha1(data).digest()).decode("ascii")


MAIN_ATTRS = (b"Manifest-Version: 1.0\r\n"
              b"Created-By: 1.0 (Android SignApk)\r\n"
              b"\r\n")


def _wrap_line(line: bytes) -> bytes:
    """Emit one logical line, broken so every physical line is <= 72 bytes
    *including* its CRLF, continuations introduced by a single leading space.

    The break is applied to the line's own bytes and never across a terminator.
    Getting this wrong is fatal in a sneaky way: splitting the stream blindly
    cuts `SHA1-Digest` in half and java.util.jar.ManifestReader then dies with
    `IOException: SHA1-Di`, surfacing as INSTALL_PARSE_FAILED_NO_CERTIFICATES.
    """
    out = b""
    first = True
    while line:
        room = 70 if first else 69          # 69 + leading space, + CRLF = 72
        chunk, line = line[:room], line[room:]
        if not first:
            chunk = b" " + chunk
        out += chunk + b"\r\n"
        first = False
    return out or b"\r\n"


def manifest_block(name: str, digest: str) -> bytes:
    """One manifest section, WITH its terminating blank line.

    The blank line is part of the section: `.SF`'s per-entry digest is taken over
    exactly these bytes (verified against the client's original GAMEPLUS.SF).
    """
    return (_wrap_line(("Name: %s" % name).encode("utf-8")) +
            _wrap_line(("SHA1-Digest: %s" % digest).encode("utf-8")) + b"\r\n")


def build_manifest(payload):
    return MAIN_ATTRS + b"".join(manifest_block(n, sha1_b64(d)) for n, d in payload)


def build_sf(manifest: bytes, payload) -> bytes:
    head = ("Signature-Version: 1.0\r\n"
            "SHA1-Digest-Manifest-Main-Attributes: %s\r\n" % sha1_b64(MAIN_ATTRS) +
            "Created-By: 1.0 (Android SignApk)\r\n"
            "SHA1-Digest-Manifest: %s\r\n\r\n" % sha1_b64(manifest)).encode("utf-8")
    body = b""
    for name, data in payload:
        section = manifest_block(name, sha1_b64(data))
        body += manifest_block(name, sha1_b64(section))
    return head + body


def parse_manifest(raw: bytes):
    """Reassemble continuation lines into {name: {attr: value}} for verification."""
    logical = []
    for line in raw.decode("utf-8").split("\r\n"):
        if line.startswith(" "):
            if logical:
                logical[-1] += line[1:]
            continue
        logical.append(line)
    out, name = {"": {}}, None
    for line in logical:
        if not line:
            name = None
            continue
        key, _, val = line.partition(": ")
        if key == "Name":
            name = val
            out.setdefault(name, {})
        else:
            out["" if name is None else name][key] = val
    return out


def sign_sf(sf_path: Path, key: str, crt: str, out_path: Path) -> bytes:
    """PKCS#7 (detached, no signed attributes) over CERT.SF - what SignApk emits.

    `-binary` stops openssl from rewriting line endings inside the signed content;
    `-noattr` matches AOSP SignApk's `setDirectSignature(true)`, which signs the
    content directly instead of an attribute set. Android's JarVerifier accepts
    exactly this shape.
    """
    subprocess.run(["openssl", "smime", "-sign", "-binary", "-noattr",
                    "-in", str(sf_path), "-signer", crt, "-inkey", key,
                    "-outform", "DER", "-out", str(out_path)],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return out_path.read_bytes()


def make_key(paths, cn="kakusen-mod"):
    """Create the self-signed signing key on first use (openssl, no JDK)."""
    key, crt = paths
    os.makedirs(os.path.dirname(key), exist_ok=True)
    if os.path.exists(key) and os.path.exists(crt):
        print("keystore exists, reusing")
        return
    subprocess.run(["openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes",
                    "-keyout", key, "-out", crt, "-days", "3650",
                    "-subj", "/CN=%s/O=kakusen/C=CN" % cn],
                   check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    print("generated key: %s" % key)


def verify(apk: Path, expected: dict) -> None:
    """Re-check what we just wrote: digests, .SF linkage, PKCS#7 and payload."""
    import random
    with zipfile.ZipFile(apk) as z:
        man_raw = z.read("META-INF/MANIFEST.MF")
        sf_raw = z.read("META-INF/%s.SF" % NEW_SIG_NAME)
        parsed = parse_manifest(man_raw)

        names = [n for n in z.namelist()
                 if not n.startswith("META-INF/") and not n.endswith("/")]
        uncovered = [n for n in names if n not in parsed]
        random.seed(7)
        sample = set(random.sample(names, min(40, len(names)))) | set(expected) | {
            "resources.arsc", "AndroidManifest.xml", "classes.dex"}
        bad = [n for n in sorted(sample)
               if n in parsed and parsed[n].get("SHA1-Digest") != sha1_b64(z.read(n))]

        sf = parse_manifest(sf_raw)
        sf_ok = sf.get("", {}).get("SHA1-Digest-Manifest") == sha1_b64(man_raw)
        main_ok = (sf.get("", {}).get("SHA1-Digest-Manifest-Main-Attributes")
                   == sha1_b64(MAIN_ATTRS))
        # .SF per-entry digests must be the digest of the manifest SECTION
        # (blank line included), which is what the original GAMEPLUS.SF does.
        sections = {}
        cursor = 0
        blocks = man_raw[len(MAIN_ATTRS):].split(b"\r\n\r\n")
        for blk in blocks:
            if blk.startswith(b"Name: ") or blk.startswith(b"Name:") and b"\r\n" in blk:
                sections[blk.split(b"\r\n", 1)[0][6:].decode()] = blk + b"\r\n\r\n"
        sec_bad = [n for n in list(sf)[1:40]
                   if n in sections and sf[n].get("SHA1-Digest") != sha1_b64(sections[n])]

    print()
    print("-- verify --")
    print("  payload entries      : %d (uncovered by manifest: %d)" % (len(names), len(uncovered)))
    print("  digest spot-check    : %d sampled, %d wrong" % (len(sample), len(bad)))
    print("  SHA1-Digest-Manifest : %s" % ("ok" if sf_ok else "MISMATCH"))
    print("  ...-Main-Attributes  : %s" % ("ok" if main_ok else "MISMATCH"))
    print("  .SF section digests  : %d checked, %d wrong" % (min(39, len(sf) - 1), len(sec_bad)))
    for n, want in expected.items():
        with zipfile.ZipFile(apk) as z:
            got = z.read(n)
        print("  %-44s %s" % (n, "patched" if got == want else "NOT PATCHED"))
    tmp = apk.parent / "_verify_tmp"
    tmp.mkdir(exist_ok=True)
    (tmp / "sf").write_bytes(sf_raw)
    (tmp / "rsa").write_bytes(zipfile.ZipFile(apk).read("META-INF/%s.RSA" % NEW_SIG_NAME))
    r = subprocess.run(["openssl", "smime", "-verify", "-binary", "-inform", "DER",
                        "-in", str(tmp / "rsa"), "-content", str(tmp / "sf"),
                        "-noverify", "-out", str(tmp / "verified")],
                       capture_output=True, text=True)
    print("  PKCS#7 over .SF      : %s" % ("ok" if r.returncode == 0 else "FAILED " + r.stderr.strip()[:80]))
    shutil.rmtree(tmp, ignore_errors=True)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--replace", action="append", default=[],
                    help="<entry name inside apk>=<local file>")
    ap.add_argument("--key", default="runtime/keys/kakusen-mod.pem")
    ap.add_argument("--cert", default="runtime/keys/kakusen-mod.crt")
    args = ap.parse_args()

    replacements = {}
    for spec in args.replace:
        name, _, local = spec.partition("=")
        replacements[name] = Path(local).read_bytes()

    make_key((args.key, args.cert))
    tmpdir = Path(args.out).parent / "_apsign_tmp"
    tmpdir.mkdir(parents=True, exist_ok=True)
    sf_tmp = tmpdir / (NEW_SIG_NAME + ".SF")
    rsa_tmp = tmpdir / (NEW_SIG_NAME + ".RSA")

    src = Path(args.src)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    signed_names = []
    payload = []            # list of (name, data) for the manifest
    replaced = 0

    with zipfile.ZipFile(src) as zin, zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED,
                                                      allowZip64=False) as zout:
        for zi in zin.infolist():
            base = zi.filename.rsplit("/", 1)[-1]
            if zi.filename.startswith("META-INF/") and (
                    base in SIG_BASENAMES or base.upper().endswith(SIG_EXTS)):
                continue                                   # old signature: drop
            data = replacements.pop(zi.filename, None)
            if data is None:
                data = zin.read(zi.filename)
            else:
                replaced += 1
                print("replaced %s (%d bytes)" % (zi.filename, len(data)))
            zout.writestr(zi, data)
            if not zi.filename.endswith("/"):
                payload.append((zi.filename, data))
                signed_names.append(zi.filename)

        if replacements:
            raise SystemExit("replacement target(s) not in apk: %s" % list(replacements))

        manifest = build_manifest(payload)
        sf = build_sf(manifest, payload)
        sf_tmp.write_bytes(sf)
        rsa = sign_sf(sf_tmp, args.key, args.cert, rsa_tmp)

        for name, data in (("META-INF/MANIFEST.MF", manifest),
                           ("META-INF/%s.SF" % NEW_SIG_NAME, sf),
                           ("META-INF/%s.RSA" % NEW_SIG_NAME, rsa)):
            zi = zipfile.ZipInfo(name, date_time=(2026, 10, 4, 12, 0, 0))
            zi.compress_type = zipfile.ZIP_DEFLATED
            zi.external_attr = 0o644 << 16
            zout.writestr(zi, data)

    shutil.rmtree(tmpdir, ignore_errors=True)

    print()
    print("entries written : %d" % len(signed_names))
    print("manifest entries: %d" % len(payload))
    print("replaced        : %d" % replaced)
    print("wrote           : %s (%.1f MB)" % (out, out.stat().st_size / 1048576.0))

    # self-check: re-open, verify the asset and the signature blobs are readable
    with zipfile.ZipFile(out) as z:
        bad = z.testzip()
        print("zip integrity   : %s" % (bad or "OK"))
        names = z.namelist()
        for n in ("META-INF/MANIFEST.MF", "META-INF/%s.SF" % NEW_SIG_NAME,
                  "META-INF/%s.RSA" % NEW_SIG_NAME):
            print("  %-28s %s" % (n, "present" if n in names else "MISSING"))
        for n in replacements:
            pass
    for n, data in payload:
        if n in replacements:
            print("patched asset   : %s = %d bytes" % (n, len(data)))

    verify(out, replacements)


if __name__ == "__main__":
    main()
